# 端口
server:
  port: ${port:9999}

# 服务名称、邮件配置、微服务配置、Redis配置
spring:
  application:
    name: gateway
  mail:
    name: WisdomCR
    username: vwanbao@163.com
    password: CRDTJNZFARCFJEQW
    host: smtp.163.com
    default-encoding: UTF-8
  boot:
    admin:
      notify:
        mail:
          to: ${spring.mail.username} # 告警收件人
          from: ${spring.mail.username} # 告警发件人
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      filter:
        # 开启/关闭对spring mav端点的保护
        enabled: true
      transport:
        dashboard: localhost:8718
      eager: true
    gateway: #配置SpringCloud GateWay相关属性
      discovery: #配置网关发现机制
        locator: #配置本地化配置机制
          enabled: true    #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true   #配置服务名大小写自动转换
  redis:
    host: 1.12.246.81
    port: 6379
    password: 123456
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-active: 8    #连接池最大连接数(使用负值表示没有限制)
        max-wait: -1     #最大阻塞等待时间(使用负值表示没有限制)
        max-idle: 8      #最大空闲连接数
        min-idle: 0      #最小空闲连接数

# 端点配置
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: '*'

white:
  ignored:
    urls:
      - /**/**/**
#      - /user/student/**
#      - /interaction/information/DetailInfoByInfoId
#      - /interaction/information/commentByInfoId
#      - /interaction/information/commentListByInfoId
#      - /interaction/information/getAllInfor
#      - /interaction/information/getAllInforByTeaId
#      - /interaction/information/getAllTotal
#      - /interaction/information/search
#      - /interaction/information/teaSearch
#      - /interaction/wenda/getAllTotal
#      - /interaction/wenda/getAllType
#      - /interaction/wenda/getAllWenDa
#      - /interaction/wenda/issueVODetail
#      - /interaction/wenda/replyVOSDetail
#      - /interaction/wenda/search
#      - /interaction/wenda/teaGetAllWenDa
#      - /interaction/wenda/teaIssueVODetail
#      - /course/course/allChapterByCouId
#      - /course/course/classQueryAllCourse
#      - /course/course/courseAppraise
#      - /course/course/courseDetail
#      - /course/course/courseDetail1
#      - /course/course/courseDetail2
#      - /course/course/courseDetail3
#      - /course/course/courseDetailByCouId
#      - /course/course/seeMore
#      - /course/course/search
#      - /course/course/recommendType
#      - /course/course/recommendCourse
#      - /progress/**/**
#      - /class/**/**
